### ISSUE TITLE
FR: Schema explorer

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [hashhashu/sqltools-Oracle-driver#1]
Is there a way to see/switch to different schemas from other users your current user has access too?

**Comment by hashhashu** [comment]
hello, do you mean you want to see different schemas in the side bar? currently I restrict it in the current user.

**Comment by hashhashu** [comment]
ok, i think it is ok to update it to show all the schemas the user can see.

**Comment by hashhashu** [comment]
Hi, I just updated, see if it satisfy your need.
