### ISSUE TITLE
How to connect as SYSDBA?

### ISSUE THREAD

**Issue by felipecrs** [hashhashu/sqltools-Oracle-driver#11]
![image](https://github.com/hashhashu/sqltools-Oracle-driver/assets/29582865/4bc16452-27c2-4374-9bf5-54232938b9a3)

I see no way to configure this.

**Comment by hashhashu** [comment]
yes， it's not supported,  i'll add it.

**Comment by hashhashu** [comment]
Hi, it's updated, please see if it works.

**Comment by felipecrs** [comment]
Thank you so much, I will check it out at maximum on Monday.

**Comment by felipecrs** [comment]
It works like a charm. Thank you so much! Tested with:

```jsonc
// .vscode/settings.json
{
  "sqltools.connections": [
    {
      "server": "127.0.0.1",
      "port": 1521,
      "driver": "Oracle",
      "username": "sys",
      "password": "sys",
      "database": "ORCLPDB1",
      "oracleOptions": {
        "privilege": "SYSDBA"
      },
      "name": "Oracle DB"
    }
  ]
}
```
