### ISSUE TITLE
EXEC not supported?

### ISSUE THREAD

**Issue by MagnusMG** [hashhashu/sqltools-Oracle-driver#2]
I tried to execute a procedure using EXEC, and got the error message 'ORA-00900: invalid SQL statement'. When I changed to CALL it worked. (Both versions work fine in SQL Developer.)

Working:
`````
CALL drop_table('MyTable');
`````

Not working:
`````
EXEC drop_table('MyTable');
`````

**Comment by hashhashu** [comment]
Yes, it hasn't supported right now, I will add it later.
Thanks.

**Comment by hashhashu** [comment]
Hi, beacuse the node-oracledb dosen't support the `exec` key word, I **replace `exec` with `call`** before processing.

**Comment by MagnusMG** [comment]
Great! Thanks!
