### ISSUE TITLE
Commit?

### ISSUE THREAD

**Issue by MagnusMG** [hashhashu/sqltools-Oracle-driver#3]
I don't seem to be able to get any updates into the database. I suspect the statement does not commit, even if I add an explicit commit.

I run the code below by first selecting the code and then pressing command-E command-E (I'm on macos). When I look in SQL Developer after that, I can see the table ttt, but it is empty.

````
CREATE TABLE ttt (
	col1 VARCHAR2(25),
	col2 VARCHAR2(25)
);

INSERT INTO ttt VALUES ('foo','bar');

COMMIT;
````

**Comment by hashhashu** [comment]
yes,&nbsp; it's&nbsp; a&nbsp; problem,&nbsp; i.will&nbsp; look&nbsp; &nbsp;it&nbsp; &nbsp;over&nbsp; &nbsp;soon.&nbsp; Thanks&nbsp; for&nbsp; support.



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 23, 2023 18:29 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [hashhashu/sqltools-Oracle-driver] Commit? (Issue #3)




 
I don't seem to be able to get any updates into the database. I suspect the statement does not commit, even if I add an explicit commit.
 
I run the code below by first selecting the code and then pressing command-E command-E (I'm on macos). When I look in SQL Developer after that, I can see the table ttt, but it is empty.
 CREATE TABLE ttt ( col1 VARCHAR2(25), col2 VARCHAR2(25) ); INSERT INTO ttt VALUES ('foo','bar'); COMMIT;

**Comment by hashhashu** [comment]
I find the reason about this issue, i will fix it maybe tomorrow and will inform you when it's updated.
Thanks for support.

**Comment by hashhashu** [comment]
Hi, it should be fixed, please update to try it, thanks.

**Comment by MagnusMG** [comment]
Thanks, that works. 

But it wold be better with auto-commit, so that I did not have to issue a separate commit every time. Would that be possible? (Or at least adding it as a setting.)

**Comment by hashhashu** [comment]
Ok, I will add it as a setting, thanks for the greate advice.
I will update it next week.

**Comment by hashhashu** [comment]
Hi, it should be added, please check it, thanks.

**Comment by MagnusMG** [comment]
It works, thanks!

**Comment by Yahud100** [comment]
hi the same issue is commin now , can u please check it once
