### ISSUE TITLE
MAC M1 

### ISSUE THREAD

**Issue by enzofrnt** [hashhashu/sqltools-Oracle-driver#4]
Hi, that not usable on mac M1. And also after installing oracledb with rosetta npm.

**Comment by hashhashu** [comment]
Hi, i'm not familiar with things that how mac M1 works and will try to figure it out tomorrow, but i think it has something to do with the install path.  In the Edit connection page,  you can click the TEST CONNECTION button and maybe can see more info. Thanks.

**Comment by hashhashu** [comment]
Hi, maybe you can try to install oracledb manually, first try to find the path by search vscode-sqltools with searching tool. And then in the data directory, install it.

**Comment by enzofrnt** [comment]
I try some things

<img width="1025" alt="Capture d’écran 2023-02-04 à 21 59 00" src="https://user-images.githubusercontent.com/63660254/216789447-49ab8427-92de-4a6b-876e-ec95c5fc642b.png">
<img width="978" alt="Capture d’écran 2023-02-04 à 21 58 07" src="https://user-images.githubusercontent.com/63660254/216789449-d61c5419-5848-4227-9618-f9ea6e638293.png">

**Comment by hashhashu** [comment]
Hi, from https://github.com/oracle/node-oracledb/issues/1349 I guess it won't work for nodejs 18, so maybe you need to install nodejs14 from homepage directly.

**Comment by enzofrnt** [comment]
mm, ok and that possible to use the right version only for oraclecdb ?

**Comment by hashhashu** [comment]
Hi, is it still not resolved ?

**Comment by enzofrnt** [comment]
obviously not

**Comment by hashhashu** [comment]
sorry for not being helpful, if you have any other questions, please let me know.

**Comment by FrauElster** [comment]
Can you bump up the version of oracledb to 6?

(Here)[https://github.com/oracle/node-oracledb/issues/1349] it is stated that it works fine with version 6 for arm64 :)

**Comment by hashhashu** [comment]
Hi, i have update oracledb to 6.0.1 and please see if it works.

**Comment by FrauElster** [comment]
It works :)
