### ISSUE TITLE
Detailed error messages

### ISSUE THREAD

**Issue by MagnusMG** [hashhashu/sqltools-Oracle-driver#7]
When I execute erroneous SQL statements (yes, I'm afraid that happens), I do not get any details, only that the statement was wrong. If I execute the same statement in SQL Developer (or using Oracle Developer Tools for VS Code) I get detailed error messages, including the line number of  the problematic code. 

Have I done something wrong in my setup, or is this a lacking feature?

**Comment by hashhashu** [comment]
Hi, now I log it in the **OUTPUT**  of  **SQLTOOLS** , I will try to make it more clear later, thanks. 
![image](https://user-images.githubusercontent.com/28927254/218106687-a03186ad-ad52-4819-a3e2-f00add8c2f73.png)

**Comment by MagnusMG** [comment]
Ah, now I see it. Thanks.

But yes, if that could be put into the same pane that you get results when you execute a valid statement, that would be great. (An indication in the SQL file to the faulty line would also be great, but that is not crucial.)

Thanks for all your work!

**Comment by hashhashu** [comment]
Hi, thanks for the great advice, it's updated.
