### ISSUE TITLE
Support of DBMS_OUTPUT

### ISSUE THREAD

**Issue by a-langer** [hashhashu/sqltools-Oracle-driver#9]
I noticed that the [DBMS_OUTPUT](https://docs.oracle.com/en/database/oracle/oracle-database/19/arpls/DBMS_OUTPUT.html) package does not output anything to the console, for example if you run:

```sql
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hello');
END;
```

Then `SQL CONSOLE: MESSAGES` will be empty. 
Is this feature not supported or am I doing something wrong?

**Comment by hashhashu** [comment]
Hi, it's updated, please see if it satisfy your needs.

**Comment by a-langer** [comment]
Judging by the commit https://github.com/hashhashu/sqltools-Oracle-driver/commit/33afe65048e0c0daaadd157211babd8d04cdda24, you added the implementation through the pipelined function. I have some concerns about this method:
- What happens if the user does not have enough rights to create types and functions in the database? In this case, the query will terminate with an error?
-  What happens if the types\functions with the names no_dorow\no_dofetch were created earlier to perform business logic? In this case, will their logic be overwritten?
-  The file [driver.ts#L164](https://github.com/hashhashu/sqltools-Oracle-driver/blob/main/src/ls/driver.ts#L164) has a check to include the string 'DBMS_OUTPUT'.  What happens when 'DBMS_OUTPUT' is called from another function\procedure and this line is not in the body of the SQL query itself? In this case, the buffer will not be read?

In this documentation https://node-oracledb.readthedocs.io/en/latest/user_guide/plsql_execution.html#using-dbms-output suggests another way  to fetch DBMS_OUTPUT with node-oracledb - bind an output string when calling the `DBMS_OUTPUT.GET_LINE()` procedure, print the string, and then repeat until there is no more data. An example implementation can be found in the [dbmsoutputgetline.js](https://github.com/oracle/node-oracledb/blob/main/examples/dbmsoutputgetline.js). This way, in my opinion, will be more universal.

**Comment by hashhashu** [comment]
Thanks for your detailed reply, i will try the way you metioned.

**Comment by hashhashu** [comment]
Hi, it's updated, see if it has any problems, thanks.

**Comment by a-langer** [comment]
I have executed the following code:
```sql
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hello1');
    DBMS_OUTPUT.PUT_LINE('Hello2');
    DBMS_OUTPUT.PUT_LINE('Hello3');
END;
```
And got the output to the console with the text of the script:
![image](https://github.com/hashhashu/sqltools-Oracle-driver/assets/15138089/0f255185-1e66-4e6d-81e4-5ece54558bd0)
The output was expected to contain three lines of text:
```text
Hello1
Hello2
Hello3
```

**Comment by a-langer** [comment]
Result set includes all messages on single line: 
![image](https://github.com/hashhashu/sqltools-Oracle-driver/assets/15138089/eb75f8ae-4788-49b4-8274-93ef4c31b5d6)
In this case the result set was expected empty, because select query not executed.

**Comment by hashhashu** [comment]
yes, I put a summary page for the not select querys, and you can see the more detailed result when you right click and choose open editor with ...
![DD486362-4591-479c-B52E-37AA0AD461E9](https://github.com/hashhashu/sqltools-Oracle-driver/assets/28927254/597ca9bc-71e3-4f43-a6ca-69f60aa0aa78)
![image](https://github.com/hashhashu/sqltools-Oracle-driver/assets/28927254/b08e96ac-03b4-49f1-a16d-5119419cd417)

**Comment by a-langer** [comment]
OK, if you open it in a text editor, then the messages are displayed correctly. But how convenient is it to open a message in a text editor every time? The DBMS_OUTPUT package is used to debug PL\SQL code, and for this you need to see the sequence of messages output to the console. As far as I understand, this view cannot display multi-line text, then it might make sense to direct the output of debug messages to a separate VSCode channel, which will be displayed on the standard "Output" tab? An example of creating a channel https://stackoverflow.com/a/58139566/19707292.

**Comment by hashhashu** [comment]
Hi, sorry for late reply, it's been busy lately.
it's updated, you can see the output in the "output" tab and choose "SQLTOOLS" channel
![image](https://github.com/hashhashu/sqltools-Oracle-driver/assets/28927254/45ebb99f-ccbd-4a7c-ad64-6a1ff4aa822d)

**Comment by hashhashu** [comment]
"Driver Oracle is not installed." i guess it has something to do with the activation rule, i accidently remove the activation sentance and only when you open a sql file it will be activated, it should be good the next update.
